# polyglot-i18n Language Cladogram Viewer
# SPDX-License-Identifier: MPL-2.0-or-later

name = "LanguageCladogram"
uuid = "a3b2c1d0-e4f5-6789-abcd-ef0123456789"
version = "0.1.0"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@gmail.com>"]

[deps]
Phylogenetics = "858c8f83-9f8a-4d79-9b0f-9d8f9e49e5d5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1.9"
